import ThemeProvider from "@/components/ThemeProvider";
import App from "@/components/App";
import "../styles/style.scss";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ThemeProvider>
        <App>{children}</App>
      </ThemeProvider>
    </html>
  );
}
